package ConvertingExceptionsWithTry

object solution01 {

}
